server:
  port: 8081
  servlet:
    context-path: /coreSimulator





# dubbo配置
#spring:
#  dubbo:
#    application:
#      # 应用名称
#      name: coreSimulator
#      # 注册中心地址 这里要填你自己zookeeper的地址
#      registry: zookeeper://127.0.0.1:2181
#    protocol:
#      # 协议端口
#      port: 20880
dubbo:
  application:
    name: coreSimulator
  registry:
    address: zookeeper://103.45.177.9:2181
  protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
    name: dubbo
    port: 20880

